### ISSUE TITLE
Internal server error when adding a new item

### ISSUE THREAD

**Issue by iGormilhit** [rero/reroils-app#42]
- Try ils.test.rero.ch (v0.1.0a15).
- Select a document.
- Add an item.
- In stead of the item editor view, get an Internal Server Error.

The error is as follow:

```
127.0.0.1 - - [27/Jun/2018 16:30:45] "GET /editor/create/item?parent_pid=10684 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/igor/.virtualenvs/reroils-app/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/igor/.virtualenvs/reroils-app/lib/python3.6/site-packages/werkzeug/wsgi.py", line 826, in __call__
    return app(environ, start_response)
  File "/home/igor/.virtualenvs/reroils-app/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/igor/.virtualenvs/reroils-app/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/igor/.virtualenvs/reroils-app/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/igor/.virtualenvs/reroils-app/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/igor/.virtualenvs/reroils-app/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/igor/.virtualenvs/reroils-app/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/igor/.virtualenvs/reroils-app/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/igor/.virtualenvs/reroils-app/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/igor/.virtualenvs/reroils-app/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/igor/.virtualenvs/reroils-app/lib/python3.6/site-packages/flask_principal.py", line 199, in _decorated
    rv = f(*args, **kw)
  File "/home/igor/.virtualenvs/reroils-app/src/reroils-record-editor/reroils_record_editor/views.py", line 91, in create
    form_options = translate(form_options, keys=keys)
  File "/home/igor/.virtualenvs/reroils-app/src/reroils-record-editor/reroils_record_editor/babel_extractors.py", line 47, in translate
    translate(v, keys)
  File "/home/igor/.virtualenvs/reroils-app/src/reroils-record-editor/reroils_record_editor/babel_extractors.py", line 44, in translate
    translate(v, keys)
  File "/home/igor/.virtualenvs/reroils-app/src/reroils-record-editor/reroils_record_editor/babel_extractors.py", line 47, in translate
    translate(v, keys)
  File "/home/igor/.virtualenvs/reroils-app/src/reroils-record-editor/reroils_record_editor/babel_extractors.py", line 44, in translate
    translate(v, keys)
  File "/home/igor/.virtualenvs/reroils-app/src/reroils-record-editor/reroils_record_editor/babel_extractors.py", line 47, in translate
    translate(v, keys)
  File "/home/igor/.virtualenvs/reroils-app/src/reroils-record-editor/reroils_record_editor/babel_extractors.py", line 44, in translate
    translate(v, keys)
  File "/home/igor/.virtualenvs/reroils-app/src/reroils-record-editor/reroils_record_editor/babel_extractors.py", line 47, in translate
    translate(v, keys)
  File "/home/igor/.virtualenvs/reroils-app/src/reroils-record-editor/reroils_record_editor/babel_extractors.py", line 44, in translate
    translate(v, keys)
  File "/home/igor/.virtualenvs/reroils-app/src/reroils-record-editor/reroils_record_editor/babel_extractors.py", line 47, in translate
    translate(v, keys)
  File "/home/igor/.virtualenvs/reroils-app/src/reroils-record-editor/reroils_record_editor/babel_extractors.py", line 42, in translate
    data[k] = _(v)
  File "/home/igor/.virtualenvs/reroils-app/lib/python3.6/site-packages/flask_babelex/__init__.py", line 623, in gettext
    return get_domain().gettext(*args, **kwargs)
  File "/home/igor/.virtualenvs/reroils-app/lib/python3.6/site-packages/flask_babelex/__init__.py", line 534, in gettext
    return t.ugettext(string) % variables
KeyError: 'icon'
```

**Comment by iGormilhit** [comment]
How to test:
1. Checkout into the [branch](https://github.com/rero/reroils-data/tree/mii-%23issue42-error-at-item-creation).
2. Run the test.
3. Load an `on_site_consultation` item detailed view.
4. Load the item, document, user, member, location editor.

**Comment by BadrAly** [comment]
Test by baa -- no errors
